### PR TITLE
Missing sqrt factor

### PR DESCRIPTION
**Pull request by paddyroddy**
from the s2let paper it looks like there is a sqrt missing
image

### CODE REVIEW

**Comment by jasonmcewen** [comment]
@paddyroddy It's possible the paper may not match precisely the definition used in the code.  There is a choice in where to put this square root so it could be factored in elsewhere in the code.  I would be very surprised if there is a missing square root factor since that would change the accuracy of the transforms.  Have you checked that an inverse followed by forward transform still give machine precision accuracy with this change?

**Comment by paddyroddy** [comment]
I can't build the matlab so no

**Comment by paddyroddy** [comment]
either way the code isn't consistent with the construction of ridgelets/curvelets

**Comment by jasonmcewen** [comment]
Indeed, it could be different to what is done for ridgelets or curvelets.  The key thing is that each type of wavelet is self consistent.  

I think it unlikely this change is correct.  The matlab version has worked correctly in the past.  Changing a square root factor in one place would break that.  So we would need to test this before seeing whether it is needed.

**Comment by paddyroddy** [comment]
I agree regarding testing but it means I'm unsure whether to put a sqrt in my code or not - I know it's just scaling but want to do it right

**Comment by jasonmcewen** [comment]
Let's move this discussion to Slack...

**Comment by paddyroddy** [comment]
Have verified that the sqrt is not there but having talked with @jasonmcewen this has been a choice of normalisation within the code so I'll close this PR

**setting up mathematica**
image

**kappa0 mathematica**
image

**kappa mathematica**
image

**python results**
image

**Pull request closed without merging**
